---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring

spec:
  releaseName: prometheus
  targetNamespace: monitoring
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      # valuesFiles: 
      #   - ./prometheus.yaml
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: monitoring
      interval: 12h
  # values:
  #   installCRDs: true
  #   controller:
  #     service:
  #       annotations:
  #         service.beta.kubernetes.io/oci-load-balancer-shape: flexible
  #         service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: 10
  #         service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: 10