apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-monitoring
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    oci-native-ingress.oraclecloud.com/protocol: HTTP
    oci-native-ingress.oraclecloud.com/backend-tls-enabled: "true"
    oci-native-ingress.oraclecloud.com/healthcheck-protocol:  "HTTP"     
    oci-native-ingress.oraclecloud.com/extract-ca-from-tls-crt: "true"
    oci-native-ingress.oraclecloud.com/policy: "ROUND_ROBIN"
    oci-native-ingress.oraclecloud.com/extract-ca-from-tls-crt: "true"
spec:
  tls:
  - hosts:
      - grafana.lag0.com.br
    secretName: lag0-monitor-certificate
  rules:
  - host: grafana.lag0.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 443