apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-monitoring
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    oci-native-ingress.oraclecloud.com/protocol: "HTTP2"
    oci-native-ingress.oraclecloud.com/policy: "ROUND_ROBIN"
    oci-native-ingress.oraclecloud.com/healthcheck-protocol:  "HTTP2"     
    oci-native-ingress.oraclecloud.com/healthcheck-port:  "80"  
    oci-native-ingress.oraclecloud.com/healthcheck-interval-milliseconds:  "10000" 
    oci-native-ingress.oraclecloud.com/healthcheck-timeout-milliseconds:  "3000" 
    oci-native-ingress.oraclecloud.com/healthcheck-retries:  "3"
    oci-native-ingress.oraclecloud.com/healthcheck-return-code:  "200"  
    oci-native-ingress.oraclecloud.com/healthcheck-response-regex:  ""  
    oci-native-ingress.oraclecloud.com/healthcheck-path:  "/health"  
    oci-native-ingress.oraclecloud.com/healthcheck-force-plaintext:  "true" 
    # oci-native-ingress.oraclecloud.com/extract-ca-from-tls-crt: "true"
spec:
  rules:
  - host: grafana.lag0.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 80