kind: Service
apiVersion: v1
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  ports:
    - name: nextcloud
      protocol: TCP
      port: 80
      targetPort: 9855
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
---
kind: EndpointSlice
apiVersion: discovery.k8s.io/v1
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    kubernetes.io/service-name: "nextcloud"
addressType: IPv4
ports:
  - name: nextcloud
    port: 9855
    protocol: TCP
endpoints:
  - addresses:
      - 179.219.137.209
    conditions:
      ready: true
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-nextcloud
  namespace: nextcloud
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - nextcloud.lag0.com.br
      secretName: lag0-nextcloud-certificate
  rules:
    - host: nextcloud.lag0.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: nextcloud
                port: 
                  number: 80
  ingressClassName: nginx