apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: flux-system
type: Opaque
data:
  password: # GITHUB USERNAME
  username: # GITHUB TOKEN
---
apiVersion: v1
data:
  identity: #=
  identity.pub: ###=
  known_hosts: #
kind: Secret
metadata:
  name: flux-system
  namespace: flux-system
type: Opaque
