apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nextcloud-mysql
  labels:
    app: nextcloud-mysql
spec:
  selector:
    matchLabels:
      app: nextcloud-mysql
  template:
    metadata:
      labels:
        app: nextcloud-mysql
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: nextcloud-mysql
        image: mysql:8.4.2
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db
                key: nextcloud-host
        ports:
          - containerPort: 3306
        resources:
          limits:
            cpu: "0.5"
            memory: "1024Mi"
          requests:
            cpu: 10m
            memory: "135Mi"