---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx

spec:
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "1.9.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 12h
  values:
    installCRDs: true
    controller.service.annotations.service.beta.kubernetes.io/oci-load-balancer-shape: flexible 
    controller.service.annotations.service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: 10
    controller.service.annotations.service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: 10