apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oci-native-ingress-controller
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./oci-native-ingress-controller
  prune: false
  force: false
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
