apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-flux-ui
  namespace: flux-system
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
    # cert-manager.io/secret-template: |
    #   {
    #     annotations: [
    #       reflector.v1.k8s.emberstack.com/reflection-allowed: "true",
    #       reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "ingress-nginx",
    #       reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true",
    #       reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "ingress-nginx"
    #     ]
    #   }
spec:
  tls:
  - hosts:
      - flux.lag0.com.br
    secretName: lag0-certificate
    secretTemplate:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "ingress-nginx"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "ingress-nginx"
  rules:
  - host: flux.lag0.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ww-gitops-weave-gitops
            port:
              number: 9001
  ingressClassName: nginx