apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-flux-ui
  namespace: flux-system
  labels:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - hosts:
      - flux.radarvoluntario.com
    secretName: radarvoluntario-certificate
  rules:
  - host: flux.radarvoluntario.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ww-gitops-weave-gitops
            port:
              number: 9001
  ingressClassName: nginx