apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-flux-ui
  namespace: flux-system
  annotations:
    kubernetes.io/ingress.class: default-ingress-class
    kubernetes.io/ingress.allow-http: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - hosts:
      - flux.lag0.com.br
    secretName: lag0-certificate
  rules:
  - host: flux.lag0.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: ww-gitops-weave-gitops
          servicePort: 9001
  ingressClassName: default-ingress-class