apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: rna-algarismos-arabicos-front-img-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: rna-algarismos-arabicos-front-img-repo
  filterTags:
    pattern: '^v(\d+\.\d+\.\d+)$'
    # extract: '$1'
  policy:
    alphabetical:
      order: asc