
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: rna-algarismos-arabicos-img-update-auto
  namespace: flux-system
spec:
  # suspend: true
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: rna-algarismos-arabicos-git
    namespace: flux-system
  git:
    commit:
      messageTemplate: |
        Image update.

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}
      author:
        name: Fluxbot
        email: flux@example.com
    checkout:
      ref:
        branch: main
    push:
      branch: main