apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cs16-surf
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cs16-surf/infra/production
  prune: false
  force: true
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
