apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
- cert-manager.yaml
- cert-manager-webhook-oci.yaml
# - duckdns-webhook.yaml
- clusterissuer-staging.yaml
- namespace.yaml
# - radar-voluntario-certificate.yaml