
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: steamcmd-zomboid
  namespace: steamcmd-zomboid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steamcmd-zomboid
  template:
    metadata:
      name: steamcmd-zomboid
      namespace: steamcmd-zomboid
      labels:
        app: steamcmd-zomboid
    spec:
      containers:
        - name: steamcmd-zomboid
          image: sonroyaalmerol/steamcmd-arm64:latest
          command: ["tail"]
          args: ["-f","/dev/null"]
          # env:
          #   - name: SHARED_DIRECTORY
          #     value: "/exports"
          # volumeMounts:
          #   - name: nfs-pv
          #     mountPath: /exports
          resources:
            limits:
              cpu: "4"
              memory: 12Gi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      # volumes:
      #   - name: nfs-pv
      #     persistentVolumeClaim:
      #       claimName: nfs-pvc