
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: steamcmd-zomboid
  namespace: steamcmd-zomboid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steamcmd-zomboid
  template:
    metadata:
      name: steamcmd-zomboid
      namespace: steamcmd-zomboid
      labels:
        app: steamcmd-zomboid
    spec:
      containers:
        - name: steamcmd-zomboid
          image: sonroyaalmerol/steamcmd-arm64:steam-2024-05-12
          command: ["tail"]
          args: ["-f","/dev/null"]
          # env:
          #   - name: SHARED_DIRECTORY
          #     value: "/exports"
          # volumeMounts:
          #   - name: nfs-pv
          #     mountPath: /exports
          # securityContext:
          #   privileged: true
      # volumes:
      #   - name: nfs-pv
      #     persistentVolumeClaim:
      #       claimName: nfs-pvc