---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  interval: 24h
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  releaseName: csi-driver-nfs
  targetNamespace: kube-system
  # install:
  #   createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.5.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: kube-system
      interval: 12h
  # values:
  #   image:
  #     tag: 8.1.0-2.1.0-aarch64