apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zomboid-server-1
  namespace: flux-system
spec:
  suspend: false
  interval: 30s
  path: ./zomboid-server-1/infra/production
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
