
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: radar-voluntario-front-img-repo
  namespace: flux-system
spec:
  image: ghcr.io/antoniolago/radar-voluntario-frontend
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: radar-voluntario-front-img-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: radar-voluntario-front-img-repo
  filterTags:
    # pattern: '.*'
    pattern: '^dev-(?P<ts>[0-9]+)'
    # -[a-z0-9]+
    extract: '$ts'
  policy:
    alphabetical:
      order: asc