
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: radar-voluntario-front-img-repo
  namespace: flux-system
spec:
  image: ghcr.io/antoniolago/radar-voluntario-front
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: radar-voluntario-front-img-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: radar-voluntario-front-img-repo
  filterTags:
    pattern: '.*-dev.*'
  policy:
    semver:
     range: '>= 0.0.0'
# ---
# apiVersion: image.toolkit.fluxcd.io/v1beta1
# kind: ImageUpdateAutomation
# metadata:
#   name: radar-voluntario-front-img-update-auto
#   namespace: flux-system
# spec:
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: radar-voluntario-dev-git
#     namespace: radar-voluntario-dev
#   git:
#     commit:
#       author:
#         name: Fluxbot
#         email: flux@example.com
#     checkout:
#       ref:
#         branch: dev
#     push:
#       branch: auto