apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-controller
  namespace: flux-system
spec:
  suspend: false
  interval: 30s
  path: ./actions-runner-controller/infra/production
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
