apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example-instance-principal
spec:
  provider:
    oracle:
      vault: # The vault OCID
      region: # The vault region
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example-auth
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.sa-saopaulo-1.ffsq7jzbaaeua.abtxeljrnhvrdgqrpggpm5a7vtbccgesalt5mer5oteqvkak7gjfxc7bon2a
      region: sa-sao-paulo-1
      auth:
        user: ocid1.user.oc1..aaaaaaaa5wcsh4c5ezax4zppd4lsc2tmbjayaytonevduefesgwdry23karq
        tenancy: antoniolago
        secretRef:
          privatekey:
            name: oracle-secret
            key: privateKey
          fingerprint:
            name: oracle-secret
            key: fingerprint
