apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: dockerconfigjson
  namespace: external-secrets
spec:
  refreshInterval: 0.03m
  externalSecretName: dockerconfigjson
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: oracle-vault-store-pessoal
    target:
      name: .dockerconfigjson
      creationPolicy: Owner
    dataFrom:
      - key: .dockerconfigjson