apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: oracle-vault-pessoal
  namespace: external-secrets
spec:
  namespaceSelector:
    matchLabels: 
      oracle.vault.pessoal: "true"
  externalSecretName: oracle-vault-pessoal
  externalSecretSpec:
    refreshInterval: 0.03m  
    secretStoreRef:
      kind: ClusterSecretStore
      name: oracle-vault-store-pessoal
    target:
      name: oracle-vault-pessoal
      creationPolicy: Owner
    # data:
    #   - secretKey: dockerconfigjson
    #     remoteRef:
    #       key: dockerconfigjson
    dataFrom:
      - key: .dockerconfigjson