apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
- vaults/pessoal/cluster-external-secrets-store.yaml
- vaults/pessoal/cluster-external-secrets.yaml
- vaults/radar-voluntario-dev/