apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
- vaults/pessoal/oracle-vault-pessoal.yaml
- external-secrets-store.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radar-voluntario-dev
resources:
- vaults/pessoal/external-secret.yaml
- vaults/radar-voluntario-dev/external-secret.yaml