apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  labels:
    app: nfs-server
spec:
  storageClassName: oci-bv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi